# Generated by Django 2.2.17 on 2021-04-03 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('head_img', models.FileField(default='article_head_img/default_head.png', help_text='文章的头图', upload_to='article_head_img/', verbose_name='头图')),
                ('title', models.CharField(help_text='文章的标题', max_length=32, verbose_name='标题')),
                ('content', models.TextField(help_text='文章的内容', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='该文章的创建时间', verbose_name='创建时间')),
                ('up_num', models.IntegerField(default=0, help_text='该文章的点赞数', verbose_name='点赞数')),
                ('description', models.CharField(help_text='简要描述该文章', max_length=128, verbose_name='摘要')),
                ('markdown', models.TextField(default='暂无', help_text='文章的Markdown内容', verbose_name='Markdown内容')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='该文章的最后修改时间', verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '文章',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(help_text='分类的名称', max_length=32, verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='评论的内容', max_length=256, verbose_name='内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, help_text='评论的时间', verbose_name='时间')),
                ('article', models.ForeignKey(help_text='评论的对象是哪篇文章', null=True, on_delete=django.db.models.deletion.CASCADE, to='anotherplanet.Article', verbose_name='文章')),
                ('comment_id', models.ForeignKey(help_text='对哪个id的评论进行评论', null=True, on_delete=django.db.models.deletion.CASCADE, to='anotherplanet.Comment', verbose_name='评论id')),
                ('user', models.ForeignKey(help_text='该评论来自哪个用户', on_delete=django.db.models.deletion.DO_NOTHING, to='anotherplanet.UserProfile', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, help_text='该文章属于哪个分类', null=True, on_delete=django.db.models.deletion.CASCADE, to='anotherplanet.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anotherplanet.UserProfile', verbose_name='文章作者'),
        ),
    ]
