# Generated by Django 2.2.17 on 2021-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotherplanet', '0003_auto_20210403_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='浏览数'),
        ),
    ]
