# Generated by Django 2.2.17 on 2021-04-03 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anotherplanet', '0004_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpAndDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(help_text='True为点赞，False为点踩', null=True, verbose_name='点赞点踩')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='点赞点踩的时间', verbose_name='创建时间')),
                ('article', models.ForeignKey(help_text='针对哪篇文章', null=True, on_delete=django.db.models.deletion.CASCADE, to='anotherplanet.Article', verbose_name='文章')),
                ('user', models.ForeignKey(help_text='来自哪个用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '点赞点踩',
            },
        ),
    ]
